### ISSUE TITLE
ERROR: cannot open `/var/mysql/database.sql' (No such file or directory)

### ISSUE THREAD

**Issue by nafg** [nkratzke/EasyMySQL#3]
Seemingly an inevitable outcome of https://github.com/nkratzke/EasyMySQL/blob/master/start-database.sh#L8

> ``` bash
> file -bi /var/mysql/database.sql
> ```

What is that line's intent?

**Comment by nkratzke** [comment]
Your are right. This line is not necessary any more (must be a 'debris' from some testing/debugging/figuring out sessions). Thanks for the hint. I removed the line.

Fixed with commit fd7cba888ef69269d0ea313ee0a82ffa9e1a36f3
